### ISSUE TITLE
Upload to Firefox extension store

### ISSUE THREAD

**Issue by 1247343406qq** [0xlau/biliplus#10]
使用Mozilla官方提供的扩展兼容性测试，结果是可以直接兼容Firefox，作者闲暇时随时上传到Firefox扩展商店吧
![Screenshot 2024-03-22 at 08-45-08 Extension Compatibility Tester](https://github.com/0xlau/biliplus/assets/90994900/c124fd85-8e47-4932-a0cc-47b5a8c5973c)

测试扩展兼容性页面：https://www.extensiontest.com/
测试结果：https://www.extensiontest.com/test/4df9fd20-e7e5-11ee-b882-1d8b22fa15ad

**Comment by 0xlau** [comment]
😄 Thanks for your testing in Firefox. If it is verified, I will upload it to the Firefox extension store later.

**Comment by 0xlau** [comment]
Now you can search this plugin in Firefox extension store.

https://addons.mozilla.org/zh-CN/firefox/search/?q=biliplus
