### ISSUE TITLE
大佬，能不能去除视频右上角的水印

### ISSUE THREAD

**Issue by hsyfly** [0xlau/biliplus#118]
![image](https://github.com/user-attachments/assets/72335435-e734-4c5f-bfab-7e241e79b0a6)
大佬，能不能增加一个功能，去除视频右上角的logo呐！！！

**Comment by oiilori** [comment]
这水印是加在视频里的，动不了

**Comment by woqucao** [comment]
去除需要调用大量计算资源做不到，不过你这个视频片段直接填色然后把水印遮住就行了

**Comment by 0xlau** [comment]
水印是加工在视频里的，没办法通过插件移除。
