### ISSUE TITLE
bilibili首页功能没有了，怎么解决？ 

### ISSUE THREAD

**Issue by SoulkyForum** [0xlau/biliplus#119]
![1](https://github.com/user-attachments/assets/5df1db14-6e14-4ac9-8344-ee67e990990f)
![2](https://github.com/user-attachments/assets/b3420334-d08f-408c-a111-4340edeeccd1)

**Comment by TheColdSummer** [comment]
是不是b站网页更新了，大家应该都失效了吧，微软插件商店大家也在问，不知道作者看到会不会更新

**Comment by 0xlau** [comment]
> 是不是b站网页更新了，大家应该都失效了吧，微软插件商店大家也在问，不知道作者看到会不会更新

肯定会更新，但最近工作有点忙，可能需要往后拖一段时间。
