### ISSUE TITLE
非常需要直接屏蔽视频作者的功能

### ISSUE THREAD

**Issue by xfwduke** [0xlau/biliplus#126]
B站自带的黑名单功能很不好用，还有数量限制

**Comment by creepebucket** [comment]
https://greasyfork.org/zh-CN/scripts/397669-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-%E5%B1%8F%E8%94%BD%E6%8C%87%E5%AE%9A%E5%86%85%E5%AE%B9
希望这个能帮到你

**Comment by xfwduke** [comment]
> https://greasyfork.org/zh-CN/scripts/397669-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-%E5%B1%8F%E8%94%BD%E6%8C%87%E5%AE%9A%E5%86%85%E5%AE%B9 希望这个能帮到你

非常感谢, 我试试看
