### ISSUE TITLE
B站搜索页改善功能

### ISSUE THREAD

**Issue by Little-fox-tail** [0xlau/biliplus#37]
B站的搜索页缺少对视频的更详细的筛选功能，可否添加视频筛选功能，或者可以另外做一个插件

例如：
1、对筛选结果的日期进行筛选，比如近一周、近一月、近一年之类的
2、B站现有时间选择仅有10分钟、10-30分钟等选项，可否做自定义，如15-25分钟之间

谢谢大佬的贡献，现有的脚本就已经帮了很大忙了。

**Comment by 0xlau** [comment]
由于搜索逻辑是b站提供的，插件只能在已呈现的内容上做二次筛选，但这样毫无意义。这个是一个好问题，但插件很难实现这个功能。
