### ISSUE TITLE
大佬为啥显示视频观看人数的功能有时候会自动关闭

### ISSUE THREAD

**Issue by phramacokonetics** [0xlau/biliplus#43]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xlau** [comment]
自动关闭意味着已经触发到b站的频繁请求接口的控制条件，原因是这个功能会大量调用同一个接口，导致b站有时候会返回出现503，这个时候需要过一会才能继续使用，所以这个功能也被标注为「谨慎使用」，目前没有什么好的方法可以解决这个问题，当然这**不会导致账号被封禁**，只是功能可能无法继续使用。
