### ISSUE TITLE
有时候没有反应

### ISSUE THREAD

**Issue by czhx123** [0xlau/biliplus#56]
已经打开了这些开关，但是“换一换”回溯功能仍不显示
![企业微信截图_20240425201511](https://github.com/0xlau/biliplus/assets/168093911/ec181fc4-e86e-4eb1-ab9c-4358f66a3b09)

**Comment by userforuser** [comment]
是不是用的chrome浏览器，我的也是回溯不显示，需要刷新网页才行，我edge的插件也是同步的但是edge就不会出现这种问题

**Comment by talentmo** [comment]
我是用EDGE的，但是也会出现不生效的情况，暂不清楚触发原因，需要重新开关插件刷新才生效
