### ISSUE TITLE
回溯功能经常不灵

### ISSUE THREAD

**Issue by LoliMilkQ** [0xlau/biliplus#64]
火狐浏览器。
主页刷新几次，回溯的按钮有时有有时没有。尝试关闭其他插件，情况没变化。

**Comment by xiaozhoui** [comment]
edge 也是 每次都要刷新一下  插件才有效果

**Comment by talentmo** [comment]
是的是的，每次不灵了都要开关一次插件再刷新，不知道什么问题。

**Comment by Mesimpler** [comment]
其实关于这个问题从代码层面来看确实有可能导致。

```js
let feedRollBtn = document.getElementsByClassName('roll-btn')[0];

if (feedRollBtn) {
// ...
}
```

`roll-btn` 这个元素是js动态生成，不一定能确保在网页onload事件结束时会被创建出来。
后面我会尝试pr修复一下。
