### ISSUE TITLE
可否适配 [BewlyBewly](https://github.com/BewlyBewly/BewlyBewly)

### ISSUE THREAD

**Issue by zhuhansan666** [0xlau/biliplus#66]
**Is your feature request related to a problem? Please describe.**
当我使用 BewlyBewly 插件时, 即使使用 BewlyBewly 兼容性选项内的原版 Bilibili 首页, biliplus 仍然 无法在首页显示换一换回溯按钮

**Describe the solution you'd like**
当 BewlyBewly 兼容性使用原版首页开启后, 本插件换一换回溯功能正常

**Describe alternatives you've considered**
尝试分析 BewlyBewly 实现并适配

**Additional context**
Nope

**Comment by 0xlau** [comment]
🤔，很遗憾地通知你，很难适配，原因是 BewlyBewly 对 b站页面完全重写，修改了大量 html 元素，所以暂时不会考虑兼容 BewlyBewly。

**Comment by InternetExplorer14** [comment]
b
