### ISSUE TITLE
谷歌浏览器回溯功能老是失效

### ISSUE THREAD

**Issue by Ailynhm** [0xlau/biliplus#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mesimpler** [comment]
能提供详细情况吗？何种失效，是按钮没有出现，还是点击按钮没有效果？

如果可以，你可以在插件失效时，按F12将控制台截图并报告在这 ）

**Comment by Ailynhm** [comment]
回溯按钮没有出现






冷丶莫雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0xlau/biliplus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [0xlau/biliplus] 谷歌浏览器回溯功能老是失效 (Issue #70)





 
Closed #70 as completed.
