### ISSUE TITLE
回溯功能不稳定

### ISSUE THREAD

**Issue by 743576324** [0xlau/biliplus#77]
**Describe the bug**
在观看哔哩哔哩网页版的时候，回溯功能并不稳定，很多时候都没有按钮，需要不停的刷新才可以出现
**To Reproduce**
打开哔哩哔哩即可重现，功能不太稳定
**Expected behavior**
每次打开哔哩哔哩网页端都能加载此功能
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  windows
 - Browser [e.g. chrome, safari]  edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0xlau** [comment]
录制一个视频看下

**Comment by Mesimpler** [comment]
这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。

**Comment by 0xlau** [comment]
只有edge才有问题吗？

**Comment by 0xlau** [comment]
> 这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。

因为我还没发布新版本，所以大家可能用的还是旧的那套

**Comment by 743576324** [comment]
> > 这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。
> 
> @Mesimpler 因为我还没发布新版本，所以大家可能用的还是旧的那套

还发现一个问题，就是这个无极倍速，观看一般UP投稿
![Uploading c1e88c3092ee684e8659dd7e5998258.png…]()
视频时可以使用，但是看综艺电影那种还是原来的倍速修改选项，我看熊出没的时候就是这样

**Comment by 743576324** [comment]
> > 这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。
> 
> @Mesimpler 因为我还没发布新版本，所以大家可能用的还是旧的那套

<img width="904" alt="c1e88c3092ee684e8659dd7e5998258" src="https://github.com/0xlau/biliplus/assets/132246173/06f014c1-333e-48dd-92d6-df860f8676fd">
这个无极倍速，观看一般视频时可以使用，但是看这种综艺动漫等官方视频时不可以使用

**Comment by 0xlau** [comment]
> > > 这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。
> > 
> > 
> > @Mesimpler 因为我还没发布新版本，所以大家可能用的还是旧的那套
> 
> <img alt="c1e88c3092ee684e8659dd7e5998258" width="904" src="https://private-user-images.githubusercontent.com/132246173/331046636-06f014c1-333e-48dd-92d6-df860f8676fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjI1NDcsIm5iZiI6MTcxNTg2MjI0NywicGF0aCI6Ii8xMzIyNDYxNzMvMzMxMDQ2NjM2LTA2ZjAxNGMxLTMzM2UtNDhkZC05MmQ2LWRmODYwZjg2NzZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMjI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTY3ZjY5Njg4ZmEwOTk4ZjYxOGE1MTM5ZTM4N2Y0YTY5MDRiNjYzZTQ4NzliZmUzNzMyZGQ0MWFkMGIxOTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LVB1JEBYteEntquLDNvnn-T6Ve5lDXRRkMzL3glsVJs"> 这个无极倍速，观看一般视频时可以使用，但是看这种综艺动漫等官方视频时不可以使用

1.0.3已经修复，可以看下

**Comment by 743576324** [comment]
> > > > 这个问题还是在频繁出现啊，我这边用chorme测试没有问题的，也不知道啥导致的。
> > > 
> > > 
> > > @Mesimpler 因为我还没发布新版本，所以大家可能用的还是旧的那套
> > 
> > 
> > <img alt="编号：c1e88c3092ee684e8659dd7e5998258" width="904" src="https://private-user-images.githubusercontent.com/132246173/331046636-06f014c1-333e-48dd-92d6-df860f8676fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjI1NDcsIm5iZiI6MTcxNTg2MjI0NywicGF0aCI6Ii8xMzIyNDYxNzMvMzMxMDQ2NjM2LTA2ZjAxNGMxLTMzM2UtNDhkZC05MmQ2LWRmODYwZjg2NzZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMjI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTY3ZjY5Njg4ZmEwOTk4ZjYxOGE1MTM5ZTM4N2Y0YTY5MDRiNjYzZTQ4NzliZmUzNzMyZGQ0MWFkMGIxOTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LVB1JEBYteEntquLDNvnn-T6Ve5lDXRRkMzL3glsVJs">这个无极倍速，观看一般视频时可以使用，但是看这种综艺动漫等官方视频时不可以使用
> 
> 1.0.3已经修复，可以看下

edge浏览器插件还是1.0.2，我下载的谷歌里的插件（1.0.3）版本，在edge里使用没有不稳定这个问题了，无极倍速也是支持了
