### ISSUE TITLE
Video list not fully loaded on initial refresh

### ISSUE THREAD

**Issue by orangelckc** [0xlau/biliplus#9]
**Is your feature request related to a problem? Please describe.**

Great work on the extension! It's really helpful. However, I've noticed a small performance issue. Upon initial refresh, the video list doesn't fully load. Specifically, the last row appears visually incomplete.

![image](https://github.com/0xlau/biliplus/assets/48410934/50902485-70d6-4a86-9ac7-b5213af3c508)

**Describe the solution you'd like**
All video covers will be loaded normally.

**Comment by 0xlau** [comment]
Absolutely right. If you are willing, PRs are welcome, otherwise I will fix it later. 👀
